                
name: CI/CD-l24z0tlbva
on: 
  push:
 
jobs:
  build-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
         image: [v-khb406f4w7,v-olchofxv2a,v-mstrb4unfk]
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image without explicit login
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: buildimage/${{matrix.image}}:latest
      - name: Verify the built image (optional)
        run: docker image ls

  build-image-v02:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
         image: [v-gmhetq68ru,v-m0h6rx3zbu,v-ht93imy5th]
    continue-on-error: true
    needs: build-image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image without explicit login
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: buildimage/${{matrix.image}}:latest
      - name: Verify the built image (optional)
        run: docker image ls

  build-image-v03:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
         image: [v-xxp94zvl31,v-tzkpiiemqr,v-hfmn6tpypm]
    continue-on-error: true
    needs: build-image-v02
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image without explicit login
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: buildimage/${{matrix.image}}:latest
      - name: Verify the built image (optional)
        run: docker image ls

  build-image-v04:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
         image: [v-k7gobgcxi1,v-fobdgn6gp9,v-of2y2gdk5p]
    continue-on-error: true
    needs: build-image-v03
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image without explicit login
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: buildimage/${{matrix.image}}:latest
      - name: Verify the built image (optional)
        run: docker image ls
